mobillogix_queue_task_index:
    path: /queued-tasks
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:index

mobillogix_queue_task_get:
    path: /queued-tasks/{id}
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:get
