mobillogix_queue_task_index:
    path: /queued-tasks
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:index

mobillogix_queue_task_get:
    path: /queued-tasks/{id}
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:get

mobillogix_queue_task_retry:
    path: /queued-tasks/{id}/retry
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:retry

mobillogix_queue_task_cancel:
    path: /queued-tasks/{id}/cancel
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:cancel

mobillogix_queue_task_execute:
    path: /queued-tasks/{id}/execute
    methods: [GET]
    defaults:
        _controller: MobillogixLaunchpadQueueBundle:Queue:execute
